// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHEWUulfSIDO-HB9I6NcmmS0E5deJDd0',
    appId: '1:704782324500:ios:8bde17af573cdde49fa801',
    messagingSenderId: '704782324500',
    projectId: 'the-odyssey-project',
    storageBucket: 'the-odyssey-project.appspot.com',
    iosBundleId: 'com.example.odysseyPlatform',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_g-OlTBHLhBY9K3LczTrlhWJQqzXkOk',
    appId: '1:704782324500:web:b8a1f170cbe497569fa801',
    messagingSenderId: '704782324500',
    projectId: 'the-odyssey-project',
    authDomain: 'the-odyssey-project.firebaseapp.com',
    storageBucket: 'the-odyssey-project.appspot.com',
    measurementId: 'G-03R4BYP490',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_g-OlTBHLhBY9K3LczTrlhWJQqzXkOk',
    appId: '1:704782324500:web:82ef41668ce27d219fa801',
    messagingSenderId: '704782324500',
    projectId: 'the-odyssey-project',
    authDomain: 'the-odyssey-project.firebaseapp.com',
    storageBucket: 'the-odyssey-project.appspot.com',
    measurementId: 'G-QDG51CNQTZ',
  );

}